routes/web.php
<?php

// frontend
Route::get('/', 'Frontend\HomepageController@index')->name('homepage');
// contact
Route::post('contact','Frontend\ContactController@sendMessage')->name('contact.send');

// auth
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// admin
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'Backend'], function () {
    // dashboard
    Route::get('dashboard','DashboardController@index')->name('admin.dashboard');
    // category
    Route::resource('category','CategoryController');
    // project
    Route::resource('project', 'ProjectController');
    // social links
    Route::resource('social-link', 'SocialLinkController');
    // intro
    Route::resource('intro', 'IntroController');
    // user info
    Route::resource('user-info', 'UserInfoController');
    // contact info
    Route::get('contact','ContactController@index')->name('contact.index');
    Route::get('contact/{id}','ContactController@show')->name('contact.show');
    Route::delete('contact/{id}','ContactController@destroy')->name('contact.destroy');
    // Sidebar user
    View::composer('backend.partials._sidebar',function ($view){
        $info = App\Models\UserInfo::all()->last();
        $view->with('info', $info);
    });
});

app/Models/Intro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Intro extends Model
{
    protected $fillable = ['first_name', 'last_name', 'background_image', 'profession', 'position'];
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Category;
use App\Models\Project;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:20|min:3',
        ]);

        $category = new Category;
        $category->name = $request->name;
        $category->save();

        Toastr::success('Category saved successfully!', 'Done');

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);
        return view('backend.category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:20|min:3',
        ]);

        $category = Category::findOrFail($id);
        $category->name = $request->name;
        $category->update();
        Toastr::success('Category updated successfully!', 'Done');

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);

        $projects = Project::where('category_id', $id);

        foreach ($projects as $project)
            if (Storage::disk('public')->exists('uploads/project/' . $project->image)) {
                Storage::disk('public')->delete('uploads/project/' . $project->image);
                $project->delete();
            }

//        foreach ($projects as $project) {
//            if (File::exists('uploads/project/' . $project->image)) {
//            dd(File::exists('/uploads/project/' . $project->image));
//                File::delete('uploads/project/' . $project->image);
//            }
//        }
//        $projects->delete();
        $category->delete();

        Toastr::success('Category deleted successfully!', 'Done');
        return redirect()->back();
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Contact;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::all();
        return view('backend.contact.index', compact('contacts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $contact = Contact::findOrFail($id);
        return view('backend.contact.show',compact('contact'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $contact = Contact::findOrFail($id);
        $contact->delete();

        Toastr::success('Contact deleted successfully!', 'Done');

        return redirect()->back();
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/IntroController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Intro;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class IntroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $intro = Intro::all()->first();
        return view('backend.intro.index', compact('intro'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.intro.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'background_image' => 'required|image',
            'profession' => 'required',
            'position' => 'required',
        ]);

        $image = $request->file('background_image');
        $slug = str_slug(config('app.name'));

        if (isset($image)) {
//            make unique name image
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!Storage::disk('public')->exists('uploads/intro')) {
                Storage::disk('public')->makeDirectory('uploads/intro');
            }
            $resizeImage = Image::make($image)->resize(1920, 695)->save();
            Storage::disk('public')->put('uploads/intro/' . $imageName, $resizeImage);
        } else {
            $imageName = 'default.png';
        }
        $intro = new Intro();

        $intro->first_name = $request->first_name;
        $intro->last_name = $request->last_name;
        $intro->background_image = $imageName;
        $intro->profession = $request->profession;
        $intro->position = $request->position;

        $intro->save();

        Toastr::success('Intro saved successfully!', 'Done');

        return redirect()->route('intro.index')->with('successMsg', 'Intro successfully saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $intro = Intro::findOrFail($id);
        return view('backend.intro.edit',compact('intro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'background_image' => 'required|image',
            'profession' => 'required',
            'position' => 'required',
        ]);

        $image = $request->file('background_image');
        $slug = str_slug(config('app.name'));

        if (isset($image)) {
//            make unique name image
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!Storage::disk('public')->exists('uploads/intro')) {
                Storage::disk('public')->makeDirectory('uploads/intro');
            }
            $resizeImage = Image::make($image)->resize(1920, 695)->save();
            Storage::disk('public')->put('uploads/intro/' . $imageName, $resizeImage);
        } else {
            $imageName = 'default.png';
        }

        $intro = Intro::findOrFail($id);

        $intro->first_name = $request->first_name;
        $intro->last_name = $request->last_name;
        $intro->background_image = $imageName;
        $intro->profession = $request->profession;
        $intro->position = $request->position;

        $intro->update();

        Toastr::success('Intro updated successfully!', 'Done');

        return redirect()->route('intro.index')->with('successMsg', 'Intro successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd($id);
    }
}

app/Http/Controllers/Backend/ProjectController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Category;
use App\Models\Project;
use Brian2694\Toastr\Facades\Toastr;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
//        $categories = Category::all();
        return view('backend.project.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('backend.project.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'category_id' => 'required',
            'name' => 'required|min:3|max:20',
            'url' => 'required',
            'image' => 'required|image',
        ]);

        $image = $request->file('image');
        $slug = str_slug($request->name);

        if (isset($image)) {
//            make unique name image
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!Storage::disk('public')->exists('uploads/project')) {
                Storage::disk('public')->makeDirectory('uploads/project');
            }
            $resizeImage = Image::make($image)->resize(400, 267)->save();
            Storage::disk('public')->put('uploads/project/' . $imageName, $resizeImage);
        } else {
            $imageName = 'default.png';
        }

        $project = new Project();

        $project->name = $request->name;
        $project->category_id = $request->category_id;
        $project->description = $request->description;
        $project->url = $request->url;
        $project->image = $imageName;

        $project->save();

        Toastr::success('Project saved successfully!', 'Done');

        return redirect()->route('project.index')->with('successMsg', 'Project successfully saved.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = Project::findOrFail($id);
        $categories = Category::all();
        return view('backend.project.edit', compact('project', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'category_id' => 'required',
            'name' => 'required|min:3|max:20',
            'url' => 'required',
            'image' => 'required|image',
        ]);

        $image = $request->file('image');
        $slug = str_slug($request->name);

        if (isset($image)) {
//            make unique name image
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '' . uniqid() . '.' . $image->getClientOriginalExtension();
            if (!Storage::disk('public')->exists('uploads/project')) {
                Storage::disk('public')->makeDirectory('uploads/project');
            }
            $resizeImage = Image::make($image)->resize(400, 267)->save();
            Storage::disk('public')->put('uploads/project/' . $imageName, $resizeImage);
        } else {
            $imageName = 'default.png';
        }

        $project = Project::findOrFail($id);

        $project->name = $request->name;
        $project->category_id = $request->category_id;
        $project->description = $request->description;
        $project->url = $request->url;
        $project->image = $imageName;

        $project->update();

        Toastr::success('Project updated successfully!', 'Done');

        return redirect()->route('project.index')->with('successMsg', 'Project successfully updated.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd($id);
    }
}

resources/views/backend/intro/create.blade.php
@extends('backend.layouts.main')

@section('title','Add Website Intro')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            ADD WEBSITE INTRO
                        </h2>
                    </div>
                    <div class="body">
                        <form action="{{route('intro.store')}}" method="post" enctype="multipart/form-data">
                            {{csrf_field()}}

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="first_name" class="form-control" name="first_name">
                                    <label class="form-label">First Name</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="last_name" class="form-control" name="last_name">
                                    <label class="form-label">Last Name</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="background_image">Background Image</label>
                                <input type="file" name="background_image" id="background_image">
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="profession" class="form-control" name="profession">
                                    <label class="form-label">Profession</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="position" class="form-control" name="position">
                                    <label class="form-label">Position</label>
                                </div>
                            </div>

                            <br>
                            <a href="{{route('intro.index')}}" type="button" class="btn btn-warning m-t-15 waves-effect">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">SAVE</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Vertical Layout | With Floating Label -->
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>
    <!-- Custom Js -->
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
@endpush

resources/views/backend/intro/edit.blade.php
@extends('backend.layouts.main')

@section('title','Edit Website Intro')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}"
          rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">
        <!-- Vertical Layout | With Floating Label -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            EDIT WEBSITE INTRO
                        </h2>
                    </div>
                    <div class="body">
                        <form action="{{route('intro.update',$intro->id)}}" method="post" enctype="multipart/form-data">
                            {{csrf_field()}}
                            {{method_field('PUT')}}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="first_name" class="form-control" name="first_name"
                                           value="{{$intro->first_name}}">
                                    <label class="form-label">First Name</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="last_name" class="form-control" name="last_name"
                                           value="{{$intro->last_name}}">
                                    <label class="form-label">Last Name</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="background_image">Background Image</label>
                                <input type="file" name="background_image" id="background_image">
                                <h3>Old Image</h3>
                                <img src="{{url('uploads/intro/',$intro->background_image)}}"
                                     alt="{{config('app.name')}}" class="img-responsive">
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="profession" class="form-control" name="profession"
                                           value="{{$intro->profession}}">
                                    <label class="form-label">Profession</label>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="position" class="form-control" name="position"
                                           value="{{$intro->position}}">
                                    <label class="form-label">Position</label>
                                </div>
                            </div>

                            <br>
                            <a href="{{route('intro.index')}}" type="button"
                               class="btn btn-warning m-t-15 waves-effect">BACK</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">UPDATE</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Vertical Layout | With Floating Label -->
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>
    <!-- Custom Js -->
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>
@endpush

resources/views/backend/intro/index.blade.php
@extends('backend.layouts.main')

@section('title','Website Intro')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush

@section('content')
    <div class="container-fluid">

        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            WEBSITE INTRO
                        </h2>
                    </div>
                    <div class="body">
                        @if (isset($intro))
                            <h4>First Name</h4>
                            <p>- {{$intro->first_name}}</p>
                            <h4>Last Name</h4>
                            <p>- {{$intro->last_name}}</p>
                            <h4>Background Image</h4>
                            <p><img src="{{url('uploads/intro/'.$intro->background_image)}}" alt="{{config('app.name')}}" class="img-responsive" /></p>
                            <h4>Profession</h4>
                            <p>- {{$intro->profession}}</p>
                            <h4>Position</h4>
                            <p>- {{$intro->position}}</p>
                            <a href="{{route('intro.edit', $intro->id)}}" type="button" class="btn btn-warning m-t-15 waves-effect">EDIT</a>
                        @else
                            <h3>No data found</h3>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>

@endpush